apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Ine4N4HSeg0=,iv:ZRSqFxgheP75/H0jRBC7zi9bkXzooRU9j5EoGxWkM98=,tag:BCbblibNvpMl27wxFV1pTw==,type:str]
    user: ENC[AES256_GCM,data:EoqbdJUVUnw=,iv:KWPIAj7EQvUYTylRsQVgkKTH0AVMPiJMvTrI/t5exyA=,tag:asJtRuag2NqLkFMXFvJ+cw==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1krtg0hd9j8vnjv3q9mjvtnuhysdax8h4s4kawpuznnulyw7dtevqwk4x0g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4em52Z2VYdmhrekZKbzlL
            eUF2SkRnd0FXcmVka2xzeC85eHduTHRsZnd3CjJrR0JaQmtnUE1qbE5QZHNzRS9Q
            TGhxczhJa1dwcThIUlF6eDBHU0Vsb0UKLS0tIG9DOWorUEU1NDBMT2dkUnZLY0xS
            UTNKcnhRV0NOaTBLUmVpOUxLWmtsTDgK9nqBcsv1EMVvD9jT6u70SM2wWwLWzKqh
            vV8w0Tj4nunfbzFHkqb5rMf0vpxj79W/oMK75FHecSiVPhXlBfzAdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T20:07:24Z"
    mac: ENC[AES256_GCM,data:nI33tPPwdiqwZpt0h+dJvS+mQtRMvBF671W5soPfeQG7lpeNfrTbqavI6x1T1zpt6REPiEd6FurXs4HRMsXrglGs7Wv9gsv8eWC3vFFCh5eHYBfcXzOGDZ6Cr/mVCPYSS/HUwgodpkF0kk2cv9BOnjHKncwnaY5BkCsaktXy1MY=,iv:BxFvVSUes9E+Dqx639xdOATpu1VBkSegui4lEgD9vRU=,tag:4QHfdJRccjCm/N+FShlfpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
